### PR TITLE
kRPC v0.4.4 updates

### PR DESCRIPTION
**Pull request by djungelorm**
This PR includes changes to update the client to work with the new features in server version 0.4.4.

Changes include:
 * Updates to protobuf schema
 * Regenerated the service specific code against server v0.4.4
 * Regenerated the documentation
 * Added second argument to KRPC.AddStream
 * Fixed some issues in the stream unit tests 

One thing that is new in v0.4.4 that isn't supported by the client (and I haven't added in this PR) is the ability to wait on events. For example, in the python client: http://krpc.github.io/krpc/python/client.html#custom-events

### CODE REVIEW

**Comment by eXigentCoder** [comment]
Thanks a lot! I'm just at the office at the moment, I'll take a look when I get home this afternoon.

**Comment by ninjaboynaru** [comment]
The ability to wait for an event can be completed using the "await" feature though it requires promises (where as callbacks are currently used).

@djungelorm I've forked your pull request and started on a wrapper library(personal usage) over krpc-node which simplifies the calls and uses promises (allows usage of await).

Thanks for updating krpc-node.

**Comment by ninjaboynaru** [comment]
**lib -> client.js -> sendRequest(...)**
Possible update to make it use both promises and callbacks
```
	if(callback) {
		client.callbackStack.splice(0, 0, callback);
	}
	else {
		return new Promise(function(resolve, reject){
			function callbackWrapper(error, response) {
				if(error) {
					reject(error);
				}
				else {
					resolve(response);
				}
			}

			client.callbackStack.splice(0, 0, callbackWrapper);
		});
	}
```

**Comment by eXigentCoder** [comment]
Thanks, I finally got a chance to play around with this PR and there are some really nice improvements in it, thank you for all your hard work!

**Pull request merged**
